networks:
  kong-net:
    driver: bridge

services:
  # 1. Auth Microservice (Using SQLite and PNPM)
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3000"
    networks:
      - kong-net
    restart: on-failure

  # 2. Product Microservice (Using SQLite and PNPM)
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3002:3000"
    networks:
      - kong-net
    restart: on-failure

  # 3. Kong Gateway (DB-less Mode)
  kong:
    image: kong:2.8.1-alpine
    container_name: kong
    environment:
      # Disable external database usage, run in DB-less mode
      KONG_DATABASE: "off" 
      # Load static configuration from kong.yml file
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml 
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8008:8000" # Proxy Port (API Gateway)
      - "8009:8001" # Admin Port (If needed)
    restart: always
    networks:
      - kong-net
    volumes:
      # Map Kong configuration file into container
      - ./kong.yml:/opt/kong/kong.yml 
    depends_on:
      - auth-service
      - product-service